version: '3.8'
networks:
  default:
      name: met
services:
  discovery-service:
    image: discovery-service
    container_name: discovery-service
    hostname: discovery-service
    expose:
      - 3007
    ports:
      - 3007:3007

  proxy:
    image: proxy
    container_name: proxy
    hostname: proxy
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - discovery-service
  
  auth-service:
    image: auth-service
    container_name: auth-service
    hostname: auth-service
    expose:
      - 3001
    ports:
      - 3001:3001
    environment:
      DB_UPSTREAM: jdbc:postgresql://${DOCKER_GATEWAY_HOST:-host.docker.internal}
    depends_on:
      - discovery-service
      - proxy
  
  account-service:
    image: account-service
    container_name: account-service
    hostname: account-service
    expose:
      - 3003
    ports:
      - 3003:3003
    environment:
      DB_UPSTREAM: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
    depends_on:
      - discovery-service
      - proxy
  
  transaction-service:
    image: transaction-service
    container_name: transaction-service
    hostname: transaction-service
    expose:
      - 3004
    ports:
      - 3004:3004
    environment:
      DB_UPSTREAM: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
    depends_on:
      - discovery-service
      - proxy